:_mod-docs-content-type: ASSEMBLY
[id="zero-trust-manager-overview"]
= Zero Trust Workload Identity Manager overview
include::_attributes/common-attributes.adoc[]
:context: zero-trust-manager-overview

toc::[]

[role="_abstract"]
The {zero-trust-full} is a {product-title} Operator that manages the lifecycle of SPIFFE Runtime Environment (SPIRE) components. It enables workload identity management based on the Secure Production Identity Framework for Everyone (SPIFFE) standard, providing cryptographically verifiable identities (SVIDs) to workloads running in {product-title} clusters.

SPIFFE can work across diverse infrastructures including on-premise, cloud, and hybrid environments. SPIFFE identities are cryptographically enabled providing a basis for auditing and compliance.

The following are components of the {zero-trust-full} architecture:

//SPIFFE
include::modules/zero-trust-manager-about-spiffe.adoc[leveloffset=+1]

//SPIRE
include::modules/zero-trust-manager-about-spire.adoc[leveloffset=+1]

//SPIRE Agent
include::modules/zero-trust-manager-about-agent.adoc[leveloffset=+1]

//Attestation
include::modules/zero-trust-manager-about-attestation.adoc[leveloffset=+1]

//== Zero Trust Workload Identity Manager components and features


