// Module included in the following assemblies:
//
// * security/external_secrets_operator/external-secrets-operator-install.adoc

:_mod-docs-content-type: CONCEPT
[id="external-secrets-operator-limitations_{context}"]
= Limitations of {external-secrets-operator}

[role="_abstract"]
The {external-secrets-operator-short} has limitations related to resource cleanup, cert-manager dependencies, and architecture support that require manual intervention during installation and uninstallation.

* Uninstalling the {external-secrets-operator} does not delete the resources created for the `external-secrets` application. You must clean up the resources manually.

* When you add the `cert-manager` Operator configurations in the `externalsecrets.operator.openshift.io` object after creation, delete the `external-secrets-cert-controller` deployment resource manually to prevent degradation of the `external-secrets` application.

* Enable the `BitwardenSecretManagerProvider` field in the `externalsecrets.operator.openshift.io` object only when installed on an OpenShift Cluster running on x86_64 and arm64 architectures.

* Ensure that the `cert-manager` Operator is installed and operational before deploying the {external-secrets-operator} for seamless functioning. If you install the `cert-manager` Operator later, manually restart the `external-secrets-operator` pod to apply the cert-manager configurations in the `externalsecrets.operator.openshift.io` object.
