// Module included in the following assemblies:
//
// * machine-configuration/mco-update-boot-images.adoc
// * nodes/nodes/nodes-update-boot-images.adoc

:_mod-docs-content-type: PROCEDURE
[id="mco-update-boot-images-configuring_{context}"]
= Enabling boot image management

[role="_abstract"]
include::snippets/mco-update-boot-images-abstract.adoc[]

If you disabled the boot image management feature, so that the boot images are not updated, you can re-enable the feature by editing the `MachineConfiguration` object.  

.Procedure

. Edit the `MachineConfiguration` object, named `cluster`, to enable the updating of boot images by running the following command:
+
[source,terminal]
----
$ oc edit MachineConfiguration cluster
----

* Optional: Configure the boot image update feature for all the machine sets:
+
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
spec:
# ...
  managedBootImages:
    machineManagers:
    - resource: machinesets
      apiGroup: machine.openshift.io
      selection:
        mode: All
----
where:

`spec.managedBootImages`:: Configures the boot image management feature.
`spec.managedBootImages.machineManagers.selection.mode`:: Specifies that all the machine sets in the cluster are to be updated.

* Optional: Configure the boot image update feature for specific machine sets:
+
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
spec:
# ...
  managedBootImages:
    machineManagers:
    - resource: machinesets
      apiGroup: machine.openshift.io
      selection:
        mode: Partial
        partial:
          machineResourceSelector:
            matchLabels:
              update-boot-image: "true"
----
where:

`spec.managedBootImages`:: Configures the boot image management feature.
`spec.managedBootImages.machineManagers.selection.partial.machineResourceSelector.matchLabels`:: Specifies that any machine set with this label is to be updated.
+
[TIP]
====
If an appropriate label is not present on the machine set, add a key-value pair by running a command similar to following:

----
$ oc label machineset.machine ci-ln-hmy310k-72292-5f87z-worker-a update-boot-image=true -n openshift-machine-api
----
====

.Verification

include::snippets/mco-update-boot-images-verification.adoc[]
