// Module included in the following assemblies:
//
// * machine-configuration/mco-update-boot-images.adoc
// * nodes/nodes/nodes-update-boot-images.adoc

:_mod-docs-content-type: PROCEDURE
[id="mco-update-boot-images-configuring_{context}"]
= Enabling boot image management

[role="_abstract"]
include::snippets/mco-update-boot-images-abstract.adoc[]

By default, for {gcp-first} and {aws-first} clusters, the Machine Config Operator (MCO) updates the boot image in the machine sets in your cluster whenever you update your cluster.

If you disabled the boot image management feature, so that the boot images are not updated, you can re-enable the feature by editing the `MachineConfiguration` object. 

For {vmw-first}, you can enable boot image management as a Technology Preview feature.

:FeatureName: Boot image management on {vmw-short}
include::snippets/technology-preview.adoc[] 

Enabling the feature updates the boot image to the current {product-title} version. If the cluster is again updated to a new {product-title} version in the future, the boot image is updated again. New nodes created after enabling the feature use the updated boot image. This feature has no effect on existing nodes.

.Prerequisites

* For {vmw-short}, enable the `TechPreviewNoUpgrade` feature set on the cluster. For more information, see "Enabling features using feature gates".

.Procedure

. Edit the `MachineConfiguration` object, named `cluster`, to enable the boot image management feature for some or all of your machine sets:
+
[source,terminal]
----
$ oc edit MachineConfiguration cluster
----

* Optional: Enable the boot image management feature for all machine sets:
+
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
spec:
# ...
  managedBootImages:
    machineManagers:
    - apiGroup: machine.openshift.io
      resource: machinesets
      selection:
        mode: All
----
where:

`spec.managedBootImages`:: Configures the boot image management feature.
`spec.managedBootImages.machineManagers.selection.mode`:: Specifies that all the machine sets in the cluster are to be updated.


* Optional: Enable the boot image management feature for specific machine sets:
+
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
spec:
# ...
  managedBootImages:
    machineManagers:
    - apiGroup: machine.openshift.io
      resource: machinesets
      selection:
        mode: Partial
        partial:
          machineResourceSelector:
            matchLabels:
              region: "east"
----
where:

`spec.managedBootImages`:: Configures the boot image management feature.
`spec.managedBootImages.machineManagers.selection.partial.machineResourceSelector.matchLabels`:: Specifies that any machine set with this label is to be updated.
+
[TIP]
====
If an appropriate label is not present on the machine set, add a key-value pair by running a command similar to following:

----
$ oc label machineset.machine ci-ln-hmy310k-72292-5f87z-worker-a region="east" -n openshift-machine-api
----
====

.Verification

. View the current state of the boot image management feature by using the following command to view the machine configuration object:
+
[source,terminal]
----
$ oc get machineconfiguration cluster -o yaml
----
+
.Example machine set with the boot image reference
[source,yaml]
----
kind: MachineConfiguration
metadata:
  name: cluster
# ...
status:
  conditions:
  - lastTransitionTime: "2025-05-01T20:11:49Z"
    message: Reconciled 2 of 4 MAPI MachineSets | Reconciled 0 of 0 CAPI MachineSets
      | Reconciled 0 of 0 CAPI MachineDeployments
    reason: BootImageUpdateConfigurationUpdated
    status: "True"
    type: BootImageUpdateProgressing
  - lastTransitionTime: "2025-05-01T19:30:13Z"
    message: 0 Degraded MAPI MachineSets | 0 Degraded CAPI MachineSets | 0 CAPI MachineDeployments
    reason: BootImageUpdateConfigurationUpdated
    status: "False"
    type: BootImageUpdateDegraded
  managedBootImagesStatus:
    machineManagers:
    - apiGroup: machine.openshift.io
      resource: controlplanemachinesets
      selection:
        mode: All
    - apiGroup: machine.openshift.io
      resource: machinesets
      selection:
        mode: All
----
+
--
where:

`status.managedBootImagesStatus.machineManagers.selection.mode`:: Specifies that the boot image management feature is enabled when set to `All`.
--

. Scale a machine set to create a new node by using a command similar to the following. The boot image is updated only for new nodes.
+
[source,terminal]
----
$ oc scale --replicas=2 machinesets.machine.openshift.io <machineset> -n openshift-machine-api
----

. If your cluster was using an older boot image version, you can see the new boot image version when the new node reaches the `READY` state. View the {op-system-first} version on a nodes:

.. Log in to the node by using a command similar to the following:
+
[source,terminal]
----
$ oc debug node/<node_name>
----

.. Set `/host` as the root directory within the debug shell by using the following command:
+
[source,terminal]
----
sh-5.1# chroot /host
----

.. View the `/sysroot/.coreos-aleph-version.json` file by using a command similar to the following:
+
[source,terminal]
----
sh-5.1# cat /sysroot/.coreos-aleph-version.json
----
+
.Example output
[source,yaml]
----
{
# ...
    "ref": "docker://ostree-image-signed:oci-archive:/rhcos-9.6.20251015-1-ostree.x86_64.ociarchive",
    "version": "9.6.20251015-1"
}
----
where:

`<version>`:: Specifies the boot image version.
