// Module included in the following assemblies:
//
// * machine_configuration/mco-update-boot-images.adoc
// * nodes/nodes-nodes-managing.adoc

:_mod-docs-content-type: PROCEDURE
[id="mco-update-boot-images-disable_{context}"]
= Disabling updated boot images

[role="_abstract"]
You can disable the boot image management feature so that the Machine Config Operator (MCO) no longer manages or updates the boot image in the affected machine sets. For example, you could disable this feature for the worker nodes in order to use a custom boot image that you do not want changed.

If you disable this feature after some nodes have been created with the new boot image version, any existing nodes retain their current boot image. Turning off this feature does not rollback the nodes or machine sets to the originally-installed boot image. The machine sets retain the boot image version that was present when the feature was enabled and is not updated again when the cluster is upgraded to a new {product-title} version in the future.

.Procedure

. Disable updated boot images by editing the `MachineConfiguration` object:
+
[source,terminal]
----
$ oc edit MachineConfiguration cluster
----

. Make the `machineManagers` parameter an empty array:
+
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
  name: cluster
  namespace: openshift-machine-config-operator
spec:
# ...
  managedBootImages:
    machineManagers: []
----
+
Remove the parameters listed under `machineManagers` and add the `[]` characters to disable boot image updates.
