// Module included in the following assemblies:
//
// * microshift_configuring/microshift-default-config-yaml.adoc
// * microshift_networking/microshift-cni.adoc.adoc

:_mod-docs-content-type: PROCEDURE
[id="microshift-yaml-default_{context}"]
= Default settings

[role="_abstract"]
When no `config.yaml` or configuration snippet exists, {microshift-short} uses built-in default values. To view these defaults, run `microshift show-config`.

The following example shows the default configuration settings.

.Procedure

*  To see the default values, run the following command:
+
[source,terminal]
----
$ microshift show-config
----
+
.Default values example output in YAML form
[source,yaml]
----
apiServer:
  advertiseAddress: 10.44.0.0/32
  auditLog:
    maxFileAge: 0
    maxFileSize: 200
    maxFiles: 10
    profile: Default
  namedCertificates:
    - certPath: ""
      keyPath: ""
      names:
        - ""
  subjectAltNames: []
debugging:
  logLevel: "Normal"
dns:
  baseDomain: microshift.example.com
etcd:
  memoryLimitMB: 0
ingress:
  listenAddress:
    - ""
  ports:
    http: 80
    https: 443
  routeAdmissionPolicy:
    namespaceOwnership: InterNamespaceAllowed
  status: Managed
kubelet:
manifests:
  kustomizePaths:
    - /usr/lib/microshift/manifests
    - /usr/lib/microshift/manifests.d/*
    - /etc/microshift/manifests
    - /etc/microshift/manifests.d/*
network:
  clusterNetwork:
    - 10.42.0.0/16
  serviceNetwork:
    - 10.43.0.0/16
  serviceNodePortRange: 30000-32767
node:
  hostnameOverride: ""
  nodeIP: ""
  nodeIPv6: ""
storage:
  driver: ""
  optionalCsiComponents:
    - ""
----
+
where:
+
--
`apiserver.advertiseAddress`:: Specifies the address of the service network.
`network.multus.status`:: Specifies the status of the Multus Container Network Interface (CNI).
`node.nodeIP`:: Specifies the IP address of the default route.
`storage.driver`:: Specifies the storage driver to use. Default null value deploys Logical Volume Managed Storage (LVMS).
`storage.optionalCsiComponents`:: Specifies the CSI components to deploy. Default null value deploys `snapshot-controller`.
--
