// Module included in the following assemblies:
//
// * microshift_storage/microshift-storage-migration.adoc

:_mod-docs-content-type: PROCEDURE
[id="microshift-making-storage-migration-request_{context}"]
= Updating stored data to the latest storage version

[role="_abstract"]
To update stored data to the latest Kubernetes storage version, perform a storage migration. 

The procedure shows an example of converting existing objects on the `v1beta1` version to the current version, such as `v1beta2`, to ensure compatibility with the cluster APIs.

.Procedure

* Either you or any controller that has support for the `StorageVersionMigration` API must trigger a migration request. Use the following example request for reference:
+
.Example request
[source,terminal]
----
apiVersion: migration.k8s.io/v1alpha1
kind: StorageVersionMigration
metadata:
  name: snapshot-v1
spec:
  resource:
    group: snapshot.storage.k8s.io
    resource: volumesnapshotclasses
    version: v1
----
+
where:
+
`resource.resource`:: Specifies the plural name of the resource.
`resource.version`:: Specifies the version to update to.

.Verification

* To monitor the progress of the update, review the status of the `StorageVersionMigration` custom resource (CR).

[NOTE]
====
A migration fails when you misname a group or resource. Incompatible versions between the previous and latest versions can also cause a migration to fail.
====