// Module included in the following assemblies:
//
//
// * migration_toolkit_for_containers/mtc-release-notes.adoc

:_mod-docs-content-type: REFERENCE
[id="migration-mtc-release-notes-1-8-13_{context}"]
= {mtc-full} 1.8.13 release notes

[role="_abstract"]
{mtc-first} 1.8.13 is a Container Grade Only (CGO) release, which is released to refresh the health grades of the containers. No code was changed in the product itself compared to that of {mtc-short} 1.8.12.


[id="enhancements-1-8-13_{context}"]
== Enhancements

{mtc-short} 1.8.13 restricts cluster upgrades beyond {product-title} 4.20::
With this update, {mtc-short} prevents {product-title} clusters from upgrading to version 4.21 and later to maintain compatibility and stability. To upgrade your cluster beyond version 4.20, uninstall {mtc-short} first. For instructions on how to uninstall {mtc-short}, see xref:../migration_toolkit_for_containers/installing-mtc#migration-uninstalling-mtc-clean-up_installing-mtc[Uninstalling {mtc-short} and deleting resources].
+
link:https://redhat.atlassian.net/browse/MIG-1872[(MIG-1872)]