// Module included in the following assemblies
//
// * storage/expanding-persistent-volumes.adoc
//* microshift_storage/expanding-persistent-volumes-microshift.adoc

:_mod-docs-content-type: PROCEDURE
[id="expanding-recovering-from-failure_{context}"]
= Recovering from failure when expanding volumes

[role="_abstract"]
To retry a failed or pending resize request, update the `spec.resources.requests.storage` field in the persistent volume claim (PVC). You must specify a value larger than the original volume size to successfully retrigger the operation.

Entering a smaller resize value in the `.spec.resources.requests.storage` field for the existing PVC does not work. 

.Procedure

. Mark the persistent volume (PV) that is bound to the PVC with the `Retain` reclaim policy. Change the `persistentVolumeReclaimPolicy` field to `Retain`.

. Delete the PVC.

. Manually edit the PV and delete the `claimRef` entry from the PV specs to ensure that the newly created PVC can bind to the PV marked `Retain`. This marks the PV as `Available`.

. Re-create the PVC in a smaller size, or a size that can be allocated by the underlying storage provider.

. Restore the reclaim policy on the PV.
