// Module included in the following assemblies:
//
// * release_notes/ocp-4-16-release-notes.adoc

:_mod-docs-content-type: REFERENCE
[id="ocp-4-16-5_{context}"]
= RHBA-2024:4855 - {product-title} {product-version}.5 fixed issues

Issued: 31 July 2024

[role="_abstract"]
{product-title} release {product-version}.5 is now available. The list of fixed issues that are included in the update is documented in the link:https://access.redhat.com/errata/RHBA-2024:4855[RHBA-2024:4855] advisory. The RPM packages that are included in the update are provided by the link:https://access.redhat.com/errata/RHSA-2024:4858[RHSA-2024:4858] advisory.

Space precluded documenting all of the container images for this release in the advisory.

You can view the container images in this release by running the following command:

[source,terminal]
----
$ oc adm release info 4.16.5 --pullspecs
----

[id="ocp-4-16-5-fixed-issues_{context}"]
== Fixed issues

* Previously, with oc-mirror plugin v2 (Technology Preview), when a generated archive was moved to a different machine, the mirroring from archive to the mirror registry operation failed and outputted the following error message:
+
[source,termninal]
----
[ERROR]: [ReleaseImageCollector] open ${FOLDER}/working-dir/hold-release/ocp-release/4.15.17-x86_64/release-manifests/image-references: no such file or directory
----
+
With this release, the machine that runs oc-mirror receives an automatic update to change its target location to the working directory. (link:https://issues.redhat.com/browse/OCPBUGS-37040[OCPBUGS-37040])

* Previously, the {oc-first} command `openshift-install destroy cluster` stalled and caused the following error message:
+
[source,terminal]
----
VM has a local SSD attached but an undefined value for 'discard-local-ssd' when using A3 instance types
----
+
With this release, after you issue the command, local SSDs are removed so that this bug no longer persists. (link:https://issues.redhat.com/browse/OCPBUGS-36965[OCPBUGS-36965])

* Previously, when the Cloud Credential Operator checked if passthrough mode permissions were correct, the Operator sometimes received a response from the {gcp-first} API about an invalid permission for a project. This bug caused the Operator to enter a degraded state that in turn impacted the installation of the cluster. With this release, the Cloud Credential Operator checks specifically for this error so that it diagnoses it separately without impacting the installation of the cluster. (link:https://issues.redhat.com/browse/OCPBUGS-36834[OCPBUGS-36834])

* Previously, with oc-mirror plugin v2 (Technology Preview), when a generated archive was moved to a different machine, the mirroring from archive to the mirror registry operation failed and outputted the following error message:
+
[source,termninal]
----
[ERROR]: [ReleaseImageCollector] open ${FOLDER}/working-dir/hold-release/ocp-release/4.15.17-x86_64/release-manifests/image-references: no such file or directory
----
+
With this release, the machine that runs oc-mirror receives an automatic update to change its target location to the working directory. (link:https://issues.redhat.com/browse/OCPBUGS-37040[OCPBUGS-37040])

[id="ocp-4-16-5-updating_{context}"]
== Updating

To update an existing {product-title} {product-version} cluster to this latest release, see xref:../updating/updating_a_cluster/updating-cluster-cli.adoc#updating-cluster-cli[Updating a cluster using the CLI].
