// Module included in the following assemblies:
//
// * release_notes/ocp-4-16-release-notes.adoc

:_mod-docs-content-type: REFERENCE
[id="ocp-4-16-21_{context}"]
= RHBA-2024:8986 - {product-title} {product-version}.21 fixed issues

Issued: 13 November 2024

[role="_abstract"]
{product-title} release {product-version}.21 is now available. The list of fixed issues that are included in the update is documented in the link:https://access.redhat.com/errata/RHBA-2024:8986[RHBA-2024:8986] advisory. The RPM packages that are included in the update are provided by the link:https://access.redhat.com/errata/RHBA-2024:8989[RHBA-2024:8989] advisory.

Space precluded documenting all of the container images for this release in the advisory.

You can view the container images in this release by running the following command:

[source,terminal]
----
$ oc adm release info 4.16.21 --pullspecs
----

[id="ocp-4-16-21-fixed-issues_{context}"]
== Fixed issues

* Previously, the installation program populated the `network.devices`, `template`, and `workspace` fields in the `spec.template.spec.providerSpec.value` section of the {vmw-full} control plane machine set custom resource (CR). These fields should be set in the {vmw-short} failure domain, and the installation program that populated them caused unintended behaviors. Updating these fields did not trigger an update to the control plane machines, and these fields were cleared when the control plane machine set was deleted.
+
With this release, the installation program is updated to no longer populate values that are included in the failure domain configuration. If these values are not defined in a failure domain configuration, for instance on a cluster that is updated to {product-title} {product-version} from an earlier version, the values defined by the installation program are used. (link:https://issues.redhat.com/browse/OCPBUGS-44179[OCPBUGS-44179])

* Previously, enabling ESP hardware offload using IPSec on attached interfaces in Open vSwitch broke connectivity due to a bug in Open vSwitch. With this release, OpenShift automatically disables ESP hardware offload on the Open vSwitch attached interfaces, and the issue is resolved. (link:https://issues.redhat.com/browse/OCPBUGS-44043[OCPBUGS-44043])

* Previously, restarting a CVO pod while it was initializing the synchronization work broke the guard of a blocked upgrade request. As a result, the blocked request was incorrectly accepted. With this release, the CVO postpones the reconciliation during the initialization step, and the issue is resolved. (link:https://issues.redhat.com/browse/OCPBUGS-43964[OCPBUGS-43964])

* Previously, if you ran RHCOS in the live environment where the `rpm-ostree-fix-shadow-mode.service` used to run, the `rpm-ostree-fix-shadow-mode.service` logged a failure that did not impact the deployment or live system. With this release, the `rpm-ostree-fix-shadow-mode.service` does not run when RHCOS is not running from an installed environment and the issue is resolved. (link:https://issues.redhat.com/browse/OCPBUGS-36806[OCPBUGS-36806])

* Previously, the installation program retrieved an unsupported VPC region when you installed a cluster on {ibm-cloud-name} into an existing VPC. Attempting to install into a supported VPC region that follows the unsupported VPC region alphabetically caused the installation program to crash. With this release, the installation program is updated to ignore any VPC regions that are not fully available during resource lookups. (link:https://issues.redhat.com/browse/OCPBUGS-36290[OCPBUGS-36290])

[id="ocp-4-16-21-updating_{context}"]
== Updating

To update an existing {product-title} {product-version} cluster to this latest release, see xref:../updating/updating_a_cluster/updating-cluster-cli.adoc#updating-cluster-cli[Updating a cluster by using the CLI].
