// Module included in the following assemblies:
//
// * release_notes/ocp-4-16-release-notes.adoc

:_mod-docs-content-type: REFERENCE
[id="ocp-4-16-9_{context}"]
= RHBA-2024:5757 - {product-title} {product-version}.9 fixed issues

Issued: 29 August 2024

[role="_abstract"]
{product-title} release {product-version}.9 is now available. The list of fixed issues that are included in the update is documented in the link:https://access.redhat.com/errata/RHBA-2024:5757[RHBA-2024:5757] advisory. The RPM packages that are included in the update are provided by the link:https://access.redhat.com/errata/RHBA-2024:5760[RHBA-2024:5760] advisory.

Space precluded documenting all of the container images for this release in the advisory.

You can view the container images in this release by running the following command:

[source,terminal]
----
$ oc adm release info 4.16.9 --pullspecs
----

[id="ocp-4-16-9-enhancements_{context}"]
== Enhancements

* The Insights Operator (IO) can now collect data from the `haproxy_exporter_server_threshold` metric.
(link:https://issues.redhat.com/browse/OCPBUGS-38230[OCPBUGS-38230])

[id="ocp-4-16-9-updating_{context}"]
== Updating

To update an existing {product-title} {product-version} cluster to this latest release, see xref:../updating/updating_a_cluster/updating-cluster-cli.adoc#updating-cluster-cli[Updating a cluster using the CLI].
